/*
 * This file was generated automatically by ExtUtils::ParseXS version 2.18_02 from the
 * contents of LibYAML.xs. Do not edit this file, edit LibYAML.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST! 
 *
 */

#line 1 "LibYAML.xs"
#include <perl_libyaml.h>
/* XXX Make -Wall not complain about 'local_patches' not being used. */
#if !defined(PERL_PATCHLEVEL_H_IMPLICIT)
void xxx_local_patches_xs() { printf("%s", local_patches[0]); }
#endif

#ifndef PERL_UNUSED_VAR
#  define PERL_UNUSED_VAR(var) if (0) var = var
#endif

#line 21 "LibYAML.c"

XS(XS_YAML__XS__LibYAML_Load); /* prototype to pass -Wmissing-prototypes */
XS(XS_YAML__XS__LibYAML_Load)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    if (items != 1)
       Perl_croak(aTHX_ "Usage: %s(%s)", "YAML::XS::LibYAML::Load", "yaml_sv");
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
	SV *	yaml_sv = ST(0);
#line 15 "LibYAML.xs"
        PL_markstack_ptr++;
        Load(yaml_sv);
        return;
#line 42 "LibYAML.c"
	PUTBACK;
	return;
    }
}


XS(XS_YAML__XS__LibYAML_Dump); /* prototype to pass -Wmissing-prototypes */
XS(XS_YAML__XS__LibYAML_Dump)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(ax); /* -Wall */
    SP -= items;
    {
#line 22 "LibYAML.xs"
        SV *dummy = NULL;
        PL_markstack_ptr++;
        Dump(dummy);
        return;
#line 66 "LibYAML.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_YAML__XS__LibYAML); /* prototype to pass -Wmissing-prototypes */
XS(boot_YAML__XS__LibYAML)
{
#ifdef dVAR
    dVAR; dXSARGS;
#else
    dXSARGS;
#endif
    char* file = __FILE__;

    PERL_UNUSED_VAR(cv); /* -W */
    PERL_UNUSED_VAR(items); /* -W */
    XS_VERSION_BOOTCHECK ;

        newXS("YAML::XS::LibYAML::Load", XS_YAML__XS__LibYAML_Load, file);
        newXS("YAML::XS::LibYAML::Dump", XS_YAML__XS__LibYAML_Dump, file);
    if (PL_unitcheckav)
         call_list(PL_scopestack_ix, PL_unitcheckav);
    XSRETURN_YES;
}

