/********************************************************************
* G__cpp_test.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error G__cpp_test.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtable();
extern void G__cpp_setup_inheritance();
extern void G__cpp_setup_typetable();
extern void G__cpp_setup_memvar();
extern void G__cpp_setup_global();
extern void G__cpp_setup_memfunc();
extern void G__cpp_setup_func();
extern void G__set_cpp_environment();
}


#include "../t1277.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__LN_vectorlEintcOallocatorlEintgRsPgR;
extern G__linked_taginfo G__LN_vectorlEfloatcOallocatorlEfloatgRsPgR;
extern G__linked_taginfo G__LN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__LN_vectorlEstringcOallocatorlEstringgRsPgR;
extern G__linked_taginfo G__LN_allocatorlEvectorlEintcOallocatorlEintgRsPgRmUgR;
extern G__linked_taginfo G__LN_vectorlEvectorlEintcOallocatorlEintgRsPgRmUcOallocatorlEvectorlEintcOallocatorlEintgRsPgRmUgRsPgR;
extern G__linked_taginfo G__LN_vectorlEvectorlEintcOallocatorlEintgRsPgRmUcOallocatorlEvectorlEintcOallocatorlEintgRsPgRmUgRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRmUcOallocatorlEvectorlEintcOallocatorlEintgRsPgRmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LN_allocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRmUgR;
extern G__linked_taginfo G__LN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRmUcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRmUgRsPgR;
extern G__linked_taginfo G__LN_vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRmUcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRmUgRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRmUcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LN_allocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRmUgR;
extern G__linked_taginfo G__LN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRmUcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRmUgRsPgR;
extern G__linked_taginfo G__LN_vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRmUcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRmUgRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRmUcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRmUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__LN_allocatorlEvectorlEstringcOallocatorlEstringgRsPgRmUgR;
extern G__linked_taginfo G__LN_vectorlEvectorlEstringcOallocatorlEstringgRsPgRmUcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRmUgRsPgR;
extern G__linked_taginfo G__LN_vectorlEvectorlEstringcOallocatorlEstringgRsPgRmUcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRmUgRsPgRcLcLiterator;
extern G__linked_taginfo G__LN_reverse_iteratorlEvectorlEvectorlEstringcOallocatorlEstringgRsPgRmUcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRmUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
typedef allocator<vector<int,allocator<int> >*> G__allocatorlEvectorlEintcOallocatorlEintgRsPgRmUgR;
typedef vector<vector<int,allocator<int> >*,allocator<vector<int,allocator<int> >*> > G__vectorlEvectorlEintcOallocatorlEintgRsPgRmUcOallocatorlEvectorlEintcOallocatorlEintgRsPgRmUgRsPgR;
typedef vector<vector<int,allocator<int> >*,allocator<vector<int,allocator<int> >*> >::iterator G__vectorlEvectorlEintcOallocatorlEintgRsPgRmUcOallocatorlEvectorlEintcOallocatorlEintgRsPgRmUgRsPgRcLcLiterator;
typedef reverse_iterator<vector<vector<int,allocator<int> >*,allocator<vector<int,allocator<int> >*> >::iterator> G__reverse_iteratorlEvectorlEvectorlEintcOallocatorlEintgRsPgRmUcOallocatorlEvectorlEintcOallocatorlEintgRsPgRmUgRsPgRcLcLiteratorgR;
typedef allocator<vector<float,allocator<float> >*> G__allocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRmUgR;
typedef vector<vector<float,allocator<float> >*,allocator<vector<float,allocator<float> >*> > G__vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRmUcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRmUgRsPgR;
typedef vector<vector<float,allocator<float> >*,allocator<vector<float,allocator<float> >*> >::iterator G__vectorlEvectorlEfloatcOallocatorlEfloatgRsPgRmUcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRmUgRsPgRcLcLiterator;
typedef reverse_iterator<vector<vector<float,allocator<float> >*,allocator<vector<float,allocator<float> >*> >::iterator> G__reverse_iteratorlEvectorlEvectorlEfloatcOallocatorlEfloatgRsPgRmUcOallocatorlEvectorlEfloatcOallocatorlEfloatgRsPgRmUgRsPgRcLcLiteratorgR;
typedef allocator<vector<double,allocator<double> >*> G__allocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRmUgR;
typedef vector<vector<double,allocator<double> >*,allocator<vector<double,allocator<double> >*> > G__vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRmUcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRmUgRsPgR;
typedef vector<vector<double,allocator<double> >*,allocator<vector<double,allocator<double> >*> >::iterator G__vectorlEvectorlEdoublecOallocatorlEdoublegRsPgRmUcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRmUgRsPgRcLcLiterator;
typedef reverse_iterator<vector<vector<double,allocator<double> >*,allocator<vector<double,allocator<double> >*> >::iterator> G__reverse_iteratorlEvectorlEvectorlEdoublecOallocatorlEdoublegRsPgRmUcOallocatorlEvectorlEdoublecOallocatorlEdoublegRsPgRmUgRsPgRcLcLiteratorgR;
typedef allocator<vector<string,allocator<string> >*> G__allocatorlEvectorlEstringcOallocatorlEstringgRsPgRmUgR;
typedef vector<vector<string,allocator<string> >*,allocator<vector<string,allocator<string> >*> > G__vectorlEvectorlEstringcOallocatorlEstringgRsPgRmUcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRmUgRsPgR;
typedef vector<vector<string,allocator<string> >*,allocator<vector<string,allocator<string> >*> >::iterator G__vectorlEvectorlEstringcOallocatorlEstringgRsPgRmUcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRmUgRsPgRcLcLiterator;
typedef reverse_iterator<vector<vector<string,allocator<string> >*,allocator<vector<string,allocator<string> >*> >::iterator> G__reverse_iteratorlEvectorlEvectorlEstringcOallocatorlEstringgRsPgRmUcOallocatorlEvectorlEstringcOallocatorlEstringgRsPgRmUgRsPgRcLcLiteratorgR;
